-- begin STAFF_PROJECT_EMPLOYEE_LINK
alter table STAFF_PROJECT_EMPLOYEE_LINK add constraint FK_PROEMP_ON_PROJECT foreign key (PROJECT_ID) references STAFF_PROJECT(ID)^
alter table STAFF_PROJECT_EMPLOYEE_LINK add constraint FK_PROEMP_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references STAFF_EMPLOYEE(ID)^
-- end STAFF_PROJECT_EMPLOYEE_LINK
